### ISSUE TITLE
fix failing test case fnocc1

### ISSUE THREAD

**Issue by psi4** [psi4/psi4public#120] opened 2015-07-15 15:02 UTC

**Comment by kannon92** [comment] 2015-07-15 16:06
fnocc1 works for me.

**Comment by bwb314** [comment] 2015-07-16 22:07
fnocc1 passes on my RHEL7 box.

**Comment by loriab** [comment] 2015-07-21 16:06
Still failing for the nightly RHEL7 conda build.

**Comment by edeprince3** [comment] 2015-07-21 16:07
Can I see the errors from RHEL7 conda?  I can't reproduce this one.

**Comment by jturney** [comment] 2015-07-21 16:27
One of my runs had one of the fnocc's failing. I'm wondering if a run
through Valgrind is needed.

Justin Turney, Ph.D.
Senior Research Scientist
CCQC/UGA

**Comment by edeprince3** [comment] 2015-07-23 14:55
I checked in changes, and it looks like fnocc1 and fnocc2 passed last night.  can this one be closed?

**Comment by loriab** [comment] 2015-07-23 15:17
Yes, fnocc looks clear across the dashboard. Go ahead and close those two.

**Closed** 2015-07-23 15:17 UTC
Labels: confirm-or-deny
