### ISSUE TITLE
fix failing test case frac

### ISSUE THREAD

**Issue by psi4** [psi4/psi4public#129] opened 2015-07-15 15:18 UTC
This has been broken for years. Test if it's still just the two points in the long array of things checked. If it's still that, perhaps consult @robparrish whether safer to drop the appearance of the frac code being present or just comment out the broken numbers.

**Comment by kannon92** [comment] 2015-07-15 19:17
It does seem that the only test cases failing are two of the test suite.

**Comment by loriab** [comment] 2015-07-15 19:26
Ok, go ahead and comment them out and make the test case work. We'll get Rob's opinion before finally closing the issue.

**Comment by loriab** [comment] 2015-07-21 21:50
Ok, I think this all goes back to the physconst update that introduced a discontinuity in the reference for two points: (wait for full load and jump) https://github.com/psi4/psi4/commit/64ea27fc1afc8fbcaf87eb03304eb8b40e99bf23#diff-4fd9a0a7922adf8bb30dbcc1278ab5d0R12 and following line (6.2 and 6.3 occ). Going to reset the reference unless @robparrish says nay. Also going to set non-zero for 6.5 occ.

**Closed** 2015-07-21 23:40 UTC
Labels: confirm-or-deny

**Comment by loriab** [comment] 2015-07-23 15:45
Looks like @jturney and @lothian  picked up some frac faults just as I’ve managed to squelch all of mine. The problem is that the scf convergence goes haywire occasionally at different fractional occupations on different computers (sometimes just failing to converge, sometimes converging to wrong values). Fiddling with `frac_start` and `mom_start` around https://github.com/psi4/psi4public/blob/master/tests/frac/input.dat#L126 for different points usually helps. If you could identify which point is giving trouble (``grep electron.``) that’d help in devising an input file that works everywhere. Or in commenting out the points most likely to offend.

https://testboard.org/cdash/viewTest.php?onlyfailed&buildid=23176
https://testboard.org/cdash/viewTest.php?onlyfailed&buildid=23168
https://testboard.org/cdash/viewTest.php?onlyfailed&buildid=23173

**Comment by loriab** [comment] 2015-11-18 17:22
frac test cast truncated to a couple points that reliably converge across computers via 9439a808a05c48b0ee3c7d319998721bd38e403b. the end.
